name: build

on:
  push:
    branches: ["main"]
    paths-ignore: ["**.md", "**/assets/modrinth/**"]
  pull_request:
    branches: ["main"]
    paths-ignore: ["**.md", "**/assets/modrinth/**"]

env:
  MINECRAFT_VERSION: 1.20.1
  JAVA_VERSION: 17
  VERSION: mc1.20.1-1.2.1-release-fabric
  VERSION_TYPE: release
  RELEASE_NAME: 1.2.1 (release) for Fabric 1.20.1
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout The Repository
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Set up JDK ${{env.JAVA_VERSION}}
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{env.JAVA_VERSION}}

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Setup Gradle for optimal use
        uses: gradle/actions/setup-gradle@v4

      - name: Generate and submit dependency graph for GiHub vulnerabilities scanner
        uses: gradle/actions/dependency-submission@v4

      - name: Build with Gradle Wrapper
        run: ./gradlew clean build

      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '17' }} # Only upload artifacts built from latest java on one OS
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
